
import { AnalyzedStatusData } from './statusAnalyzer';
import { formatNumber, formatPercent } from './formatters';

// Helper to convert the specific HTML structure of AI insights to Structured Markdown
const convertHtmlToMarkdown = (html: string): string => {
  if (!html) return "";

  let md = html;
  
  // 0. Pre-clean: Remove comments
  md = md.replace(/<!--[\s\S]*?-->/g, ''); 
  
  // 1. Semantic Mapping: Product Portrait
  md = md.replace(
    /(?:<span[^>]*>\s*📦\s*<\/span>\s*)?<h3[^>]*>\s*(?:📦)?\s*产品画像与基本情况\s*<\/h3>[\s\S]*?<div[^>]*class="p-6"[^>]*>\s*<p[^>]*>/gi, 
    '\n### 📦 产品画像与基本情况\n> '
  );

  // 2. Semantic Mapping: Diagnosis Matrix Header
  md = md.replace(/(<span[^>]*>1\. 标题描述.*?<\/span>)/, '\n---\n\n### 🛡️ 深度归因诊断矩阵\n\n$1');

  // 3. Semantic Mapping: Row Headers
  md = md.replace(/<span[^>]*>(1\. 标题描述.*?)<\/span>/g, '#### $1');
  md = md.replace(/<span[^>]*>(2\. 五点描述.*?)<\/span>/g, '#### $1');

  // 4. Linearization: Flatten the Grid Columns
  md = md.replace(/<h4[^>]*>\s*问题分析：\s*<\/h4>/g, '\n**❌ 问题诊断 (Root Cause)**:');
  md = md.replace(/<h4[^>]*>\s*优化逻辑：\s*<\/h4>/g, '\n**💡 优化思路**:');
  md = md.replace(/<h4[^>]*>\s*优化建议：\s*<\/h4>/g, '\n**✅ 优化建议 (Action Plan)**:');

  // 5. Tag Conversion
  md = md.replace(/<ul[^>]*>/g, '');
  md = md.replace(/<\/ul>/g, '\n');
  md = md.replace(/<li[^>]*>\s*/g, '\n* '); 
  md = md.replace(/<\/li>/g, '');

  md = md.replace(/<strong[^>]*>(.*?)<\/strong>/g, '**$1**');
  md = md.replace(/<b[^>]*>(.*?)<\/b>/g, '**$1**');

  md = md.replace(/<p[^>]*>/g, '');
  md = md.replace(/<\/p>/g, '\n\n');
  md = md.replace(/<div[^>]*>/g, '\n'); 
  md = md.replace(/<\/div>/g, '\n');

  md = md.replace(/🚫 根本原因.*?\(Root Cause\)/g, '');
  md = md.replace(/✅ 行动建议.*?\(Action Plan\)/g, '');

  md = md.replace(/<[^>]+>/g, '');
  md = md.replace(/\n\s*\n\s*\n/g, '\n\n');
  md = md.replace(/\n\*\s+/g, '\n* ');
  md = md.split('\n').map(line => line.trim()).join('\n');
  
  return md.trim();
};

export const generateStatusMarkdown = (data: AnalyzedStatusData, aiInsights?: Record<string, string>): string => {
  const { narrative, statistics, groups, entities } = data;
  const isPurchase = data.reportMode === 'purchase';

  // --- Helper to generate ASIN tables ---
  const generateAsinTable = (items: any[], showStatusIcon = false) => {
    if (items.length === 0) return '_暂无数据_';
    
    let header = `| ASIN | Sales Share | Returns Share | Return Rate |${showStatusIcon ? ' Status |' : ''}\n`;
    header += `| :--- | :--- | :--- | :--- |${showStatusIcon ? ' :--- |' : ''}\n`;
    
    const rows = items.map(item => {
      const rateStr = formatPercent(item.returnRate);
      const isRisk = item.returnRate > 0.1;
      const rateCell = isRisk ? `**${rateStr}**` : rateStr;
      const statusCell = showStatusIcon ? ` ${item.statusIcon} ${item.statusLabel} |` : '';
      
      return `| ${item.asin} | ${formatPercent(item.salesShare)} | ${formatPercent(item.returnsShare)} | ${rateCell} |${statusCell}`;
    }).join('\n');

    return header + rows;
  };

  let markdown = `# ${data.reportTitle}
> **Generated by**: Returns Insight Pro
> **Date**: ${data.reportDate}
> **Scope**: ${narrative.country} Station | Parent ASIN: \`${narrative.fasin}\` | Period: ${narrative.period}
> **Methodology**: ${data.methodology}

`;

  // Render Data Integrity Warning Block
  if (data.integrityWarning?.isIncomplete) {
    markdown += `> ⚠️ **数据完整性预警 (Data Integrity Warning)**
> 统计结束日期距今不足 30 天，由于亚马逊退货存在时间滞后（Return Lag），近期的退货数据尚未完全回流。
> **当前报告中的退货率数据可能偏低，仅供参考，不建议作为最终考核依据。**
> *预计数据完全沉淀还需约 ${data.integrityWarning.daysToWait} 天。*

`;
  }

  markdown += `## 1. Narrative (叙事层 - 业务全景)

**Health Status**: ${narrative.healthEmoji} **${narrative.healthLabel} (${narrative.healthStatus})**
**Attribution Logic**: ${isPurchase ? '🛒 Based on Order Date (下单归因)' : '📅 Based on Return Event (退货归因)'}
*${isPurchase ? 'Cohort Return Rate' : 'Current Return Rate'} ${statistics.returnRateFormatted} vs. Threshold 10%*

**Strategic Overview (业务解读)**:
> ${narrative.strategicOverview}

---

## 2. Statistics (统计层 - 结构化分布)

### 2.1 Global Metrics (核心指标)
| Metric | Value |
| :--- | :--- |
| **Total Units Sold** | **${formatNumber(statistics.totalSold)}** |
| Total Returns | ${formatNumber(statistics.totalReturns)} |
| **${isPurchase ? 'Cohort Return Rate (批次退货率)' : 'Blended Return Rate (综合退货率)'}** | **${statistics.returnRateFormatted}** |

### 2.2 Structural Segmentation (阵营拆解)

${groups.classA.count > 0 ? `#### 🔵 Class A: Main Battlefield (主战场款)
*   **Summary**: 本期共有 **${groups.classA.count}** 个核心 ASIN。
*   **Impact**: 合计贡献销量 **${formatPercent(groups.classA.totalSalesShare)}** | 退货量 **${formatPercent(groups.classA.totalReturnsShare)}**。
*   **Insight**: ${groups.classA.insight}

**ASIN Detail List**:
${generateAsinTable(groups.classA.items, true)}` : `#### 🔵 Class A: Main Battlefield (主战场款)
> *本期未识别到核心主战场款 ASIN。*`}

${groups.classB.count > 0 ? `#### 🔴 Class B: Problematic High-Risk (高退货问题款)
*   **Summary**: 本期共有 **${groups.classB.count}** 个高退货问题 ASIN。
*   **Impact**: 合计销量占比 **${formatPercent(groups.classB.totalSalesShare)}** | 退货占比 **${formatPercent(groups.classB.totalReturnsShare)}**。
*   **Critical Metric**: **该组平均退货率为 ${formatPercent(groups.classB.avgReturnRate)} (显著高于父体 ${statistics.returnRateFormatted})**。
*   **Insight**: ${groups.classB.insight}

**ASIN Detail List**:
${generateAsinTable(groups.classB.items, false)}` : `#### 🔴 Class B: Problematic High-Risk (高退货问题款)
> ✅ **Good Job!** 本期表现良好，未发现高退货问题款 ASIN。`}

${groups.watchlist.count > 0 ? `#### 🟡 Watchlist (高退货观察对象)
*   **Summary**: 共有 **${groups.watchlist.count}** 个小体量 ASIN 纳入观察。
*   **Impact**: 合计贡献销量 **${formatPercent(groups.watchlist.totalSalesShare)}** | 退货量 **${formatPercent(groups.watchlist.totalReturnsShare)}**。
*   **Insight**: ${groups.watchlist.insight}

**ASIN Detail List**:
${generateAsinTable(groups.watchlist.items, false)}` : `#### 🟡 Watchlist (高退货观察对象)
> *本期暂无新增高退货观察对象。*`}

---

## 3. Entities (实体层 - 深度归因与诊断)

> 本部分针对 **Class A** 与 **Class B** 中的重点 ASIN 进行详细拆解。

${entities.map(entity => {
  const topReason = entity.topReasons[0] || { name: 'N/A', pct: 0, count: 0 };
  
  // Generate Table Rows for Top 3 Reasons
  const topReasonsRows = entity.topReasons.slice(0, 3).map((r, i) => {
      const isFirst = i === 0;
      const name = isFirst ? `**${r.name}**` : r.name;
      const pct = isFirst ? `**${formatPercent(r.pct)}**` : formatPercent(r.pct);
      return `| ${i + 1} | ${name} | ${pct} | ${r.count} |`;
  }).join('\n');

  const existingInsightHtml = aiInsights ? aiInsights[entity.asin] : null;

  return `### 📦 ASIN: ${entity.asin}
*   **Tag**: ${entity.problemClass === 'B' ? '🔴' : '🔵'} ${entity.problemClassLabel}
*   **Metrics**: Returns: ${formatNumber(entity.unitsReturned)} | Coverage: ${formatPercent(entity.textCoverage)}
*   **Confidence**: ${entity.confidenceLevel} (${entity.confidenceLabel}) - Based on ${entity.totalEvents} events

#### 3.1 Top Return Reasons (数据归因)
| Rank | Reason Code | Pct | Event Count |
| :--- | :--- | :--- | :--- |
${topReasonsRows}

#### 3.2 User Voice Evidence (用户原声透视)
${entity.evidenceText 
  ? entity.evidenceText.split('\n').map(line => `> *${line}*`).join('\n') 
  : '> _暂无足够的用户原声数据_'}

#### 3.3 🤖 AI Intelligence Context (智能归因诊断)

${existingInsightHtml 
  ? convertHtmlToMarkdown(existingInsightHtml) 
  : `*(未在 UI 中生成 AI 诊断，以下提供 Context 供 AI Agent 读取)*

**[Context A] Listing Claims (产品承诺)**
*   **Title**: ${entity.listingContext?.title || "N/A"}
*   **Key Features (Bullet Points)**:
${entity.listingContext?.features ? entity.listingContext.features.split('\n').map(f => `    * ${f}`).join('\n') : "    * N/A"}
*   **Product Description**:
    > ${entity.listingContext?.description ? entity.listingContext.description.replace(/\n/g, ' ') : "N/A"}

**[Context B] Diagnosis Protocol (诊断指令)**
*   **Input 1**: Context A (Marketing Claims)
*   **Input 2**: Section 3.2 (User Evidence: "${topReason.name}")
*   **Task**: 
    1.  **Cross-Check**: Contrast the user feedback with the specific bullet points above. 
    2.  **Root Cause**: Is this a "Quality Failure" (product broke) or "Expectation Gap" (misleading description)?
    3.  **Action**: Suggest specific edits to the Listing text to manage expectations (e.g. "Add compatibility note to Bullet Point #2").`}
`;
}).join('\n\n---\n\n')}

---
*End of Report*
`;

  return markdown;
};
